### ISSUE TITLE
Allow hubot-grafana to connect to custom S3 endpoints

### ISSUE THREAD

**Issue by GrandPubba** [stephenyeargin/hubot-grafana#38]
Currently hubot-grafana can only connect to an Amazon S3 endpoint.  Knox the underlying library that allows custom S3 endpoints this feature would allow hubot-grafana to utilize this feature.

**Comment by stephenyeargin** [comment]
Some quick notes on this one:

@zyegfryed added this ability in #35 (and I see you've got some work on it in #39). Of interesting note, there was a request in #37 to stop using `knox` because it was missing support for certain AWS IAM settings (notably to automatically infer a connection from a particular host).

**Comment by GrandPubba** [comment]
Thanks for the quick reply.  Let me rebase my patch on the most recent code and resubmit.  There is a minor "bug" in the current version that will always links to an https URL even if the S3 endpoint is not secure.  This patch also allows you to use a non-standard port and choose the type of bucket style you want to use.  All things that aren't admittedly super critical once the bot is deployed in product but came up when testing in my local environment.

**Comment by GrandPubba** [comment]
OK I rebased and submitted a new pull request #40.  I would also note that in relation to #35 the tests in this request may help when making the proposed upgrade.

**Comment by stephenyeargin** [comment]
Word. Made some general notes #40.

**Comment by stephenyeargin** [comment]
Closed via #40
