### ISSUE TITLE
Slack file upload support

### ISSUE THREAD

**Issue by misterdai** [stephenyeargin/hubot-grafana#47]
Feature request for this module to also support Slack when it comes to uploading the images.  I've already created a fork with the required changes (hubot-grafana-slack), but it'd be fantastic to see them merged in if others would find it useful.  I've implemented it in much the same way as S3 support, checking for a Slack token which informs the module to upload the file to the relevant Slack instead.  Currently still have to fix up a test script for my changes but it's working well for my uses so far.

**Comment by stephenyeargin** [comment]
Yeah, the blocker for this so far has been assuring that everything continues to work with the various adapters. Hubot does not have great internal handling of the concept of an "envelope" (or whatever Hipchat/etc. calls it) so that the adapters can do the right thing™. PR #27 from @klynch offers similar functionality, but I had blocked it from merging for the reasons above.

If we can check all these off, it would be golden:

- IRC or shell users can continue to use the S3 adapter
- HipChat/Rocketchat/Slack adapter users have a single interface to their respective adapters for posting images natively
- New chat services (seems like a new one comes along every day) can follow the same pattern

**Comment by misterdai** [comment]
The route I went with was ignoring what adapter might be in use, as from what I can tell the current slack adapter doesn't handle file uploads at the moment.  So the Slack API Token is kept under the `HUBOT_GRAFANA_` naming convention, then it's a simple post request with the file contents.  That way, any IRC or other adapters will ignore the Slack code unless that environmental variable is present.

Could probably be implemented better if you were thinking of supporting even more services, at the moment it's just an additional if statement to check for the slack token vs S3 details.

**Comment by stephenyeargin** [comment]
>Could probably be implemented better if you were thinking of supporting even more services, at the moment it's just an additional if statement to check for the slack token vs S3 details.

Yeah, simply from a roadmap perspective, I wanted to make it as universal as possible. I know that @torkelo has a desire to have a [Slack specific integration in the future](http://docs.grafana.org/tutorials/hubot_howto/). From that post:

>Grafana is going to ship with integrated Slack and Hipchat features some day but you do not have to wait for that.

So this package won't even be the preferred way to integrate with Slack at some point down the road.

**Comment by stephenyeargin** [comment]
Now that `robot.adapterName` is exposed somewhat reliably in updated Hubots, we could conceivably begin trying to roll back in some of the features created in forks like [this one](https://github.com/fuzzyorange/hubot-grafana-slack#readme).

**Comment by misterdai** [comment]
That'll be my fork :) Feel free to take from it anything worthwhile.

**Comment by stephenyeargin** [comment]
#58 appears to have closed this one out to allow uploads over the Slack API.
