### ISSUE TITLE
Image uploads to S3 bucket with zero size.

### ISSUE THREAD

**Issue by SURAJTHEGREAT** [stephenyeargin/hubot-grafana#56]
Hi
I am successfully able to put .png file to S3 bucket , but size is zero bytes.

[Fri May 19 2017 05:21:52 GMT+0000 (UTC)] DEBUG Uploading file: 27032 bytes, content-type[image/png]
[Fri May 19 2017 05:21:52 GMT+0000 (UTC)] DEBUG filename
[Fri May 19 2017 05:21:52 GMT+0000 (UTC)] DEBUG graphs/59515bcabb9abb59c31ab44a0b3557635238aa10.png
[Fri May 19 2017 05:21:55 GMT+0000 (UTC)] DEBUG inside response

But  _header: 'POST /<bucket-name> /graphs/59515bcabb9abb59c31ab44a0b3557635238aa10.png upload in S3 is zero bytes,

Can anyone say where does it store the png file locally ?

**Comment by stephenyeargin** [comment]
So the file is loaded into memory after being retrieved from your Grafana instance rather than written to disk (the images are usually fairly small). One thing to check is to make sure that the PNG file is rendering correctly when you directly visit visit the "Direct link rendered image" link when clicking "Share" on a particular graph.

![screen shot 2017-05-19 at 5 16 00 pm](https://cloud.githubusercontent.com/assets/80459/26268857/ebd3e7b8-3cb6-11e7-8987-cbbe5e396e39.png)

**Comment by stephenyeargin** [comment]
Closing this off since it's a bit stale. Let me know if you are still having trouble with it.
